# site name
prefixName: Winnie
siteName: ''
# favicon and site master avatar
favicon: /images/favicon.ico
avatar: /images/home/avatar.jpg

description: All our life, we are about to get rid of the expectations of others to find the true self. Even if my efforts are not rewarded, I will face everything positively.
cdn: https://cdn.jsdelivr.net/gh/honjun/cdn@1.6
pjax: 1
# 1开启
mathjax: 0

# notice: hexo-Sakura主题已经开源，目前正在开发中...
lazyloadImg: https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/loader/orange.progress-bar-stripe-loader.svg

menus:
  Home: { path: /, fa: fa-home faa-shake  }
  Profile: { path: /Profile, fa: fa-archive faa-shake }
  CV: { path: /CV, fa: fa-mortar-board faa-shake }
  Hobbies: { path: /Hobbies, fa: fa-inbox faa-shake }
  Project: { path: /Project, fa: fa-list-alt faa-shake }
  # Music: { path: /Music, fa: fa-music faa-shake }
  Life: { path: /Life, fa: fa-joomla faa-shake }
# menus:
#   - { key: "Home", path: "/",}
#   - { key: "Profile", path: "/Profile/" }
#   - { key: "CV", path: "/CV/"}
#   - { key: "Hobbies", path: "/Hobbies/" }
#   - { key: "Project ", path: "/Project/"}
#   - { key: "Music", path: "/Music/" }
#   - { key: "Life", path: "/Life/" }

# Home page sort type: -1: newer first，1: older first.
homePageSortType: -1
# Home page article shown number)
homeArticleShown: 10
# 背景图片 更好的修改
bg:
  - /images/cover/1.jpg
  - /images/cover/2.jpg
  - /images/cover/3.jpg
  - /images/cover/4.jpg


# 背景图片样式 空 原图效果 filter-dim 阴影 filter-grid 横条 filter-dot 点点
bgclass: filter-dot

# startdash url, title, desc img




# your site build time or founded date
siteBuildingTime: 11/18/2024

#social  url, img PC端配置
social:
  github: {url: http://github.com/Winnie051203, img: /img/social/github.png}
  # sina: {url: http://weibo.com/mashirozx?is_all=1, img: /img/social/sina.png}


#social  url, img 移动端配置
msocial:
  github: {url: http://github.com/winnie051203, fa: fa-github, color: 333}


# donate:
#   paypal: https://www.paypal.me/hojuncn
#   alipay: /img/custom/donate/AliPayQR.jpg
#   wechat: /img/custom/donate/WeChanQR.jpg
#   wechatSQ: /img/custom/donate/WeChanSQ.jpg

# 视频地址为https://cdn.jsdelivr.net/gh/honjun/hojun@1.2/Unbroken.mp4，配置如下
movies:
  url: https://cdn.jsdelivr.net/gh/honjun/hojun@1.2
  # 多个视频用逗号隔开，随机获取。支持的格式目前已知MP4,Flv。其他的可以试下，不保证有用
  name: Unbroken.mp4

aplayer: 
  id: 2660651585
  server: netease
  type: playlist
  fixed: true
  autoplay: false
  loop: all
  order: random
  preload: auto
  volume: 0.7
  mutex: true

# Valine
valine: true
v_appId: GyC3NzMvd0hT9Yyd2hYIC0MN-gzGzoHsz
v_appKey: mgOpfzbkHYqU92CV4IDlAUHQ

# Waline
waline:
  enable: false
  serverURL: #服务端地址
  visitor: false #统计阅读量
  comment_count: true #统计评论数
  avatar: mp # Gravatar style : mp/identicon/monsterid/wavatar/retro/hide
  guest_info: nick #,mail,link # custom comment header
  pageSize: 10
  placeholder: 祝开开心心！ # Comment Box placeholder
  requiredFields: [ 'nick','mail' ] #设置必填项
  background: https://gitee.com/cungudafa/source/raw/master/img/gif/Sitich/Sitich2.gif #输入框提示动画